language: node_js
node_js:
  - lts/*
  - node
script: npm run test:ci
jobs:
  include:
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
